### ISSUE TITLE
Is the spec-internal built-in generator going to start in this proposal?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-iterator-helpers#104]

**Comment by devsnek** [comment]
Yield(X) is:

1. Let generatorKind be ! GetGeneratorKind().
1. If generatorKind is async, then return ? AsyncGeneratorYield(X).
1. Otherwise, return ? GeneratorYield(CreateIterResultObject(X, false)).

**Comment by Jack-Works** [comment]
Eh, I mean the builtin generator presented in the last meeting https://docs.google.com/presentation/d/1QVW_d4lpiFQ5X5czGWq0VMRN9cMLIGpt888TQoyFWpg/edit#slide=id.g85fbc47327_0_62

**Comment by devsnek** [comment]
The plan is built-in generators that use a duplicate version of the existing generator infra in the spec. They behave like generators but they aren't instances of generators.

**Comment by Jack-Works** [comment]
https://github.com/tc39/ecma262/pull/2045
