### ISSUE TITLE
toMap and toSet

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-iterator-helpers#125]
Just like toArray, I think we should have it. Not too late before we go to the stage 3

**Comment by bakkot** [comment]
See previous discussion in e.g. https://github.com/tc39/proposal-iterator-helpers/issues/36#issuecomment-521034823 and https://github.com/tc39/proposal-iterator-helpers/issues/17.

Personally I don't think anything other than `toArray` should be in this proposal. The problem of constructing collections in general is a [much larger space](https://github.com/tc39/proposal-object-iteration/issues/11#issuecomment-580065197);  as mentioned in the above-linked comment, `Array` really is uniquely privileged in a way that `Map` and `Set` are not.

(Also, I'm not convinced that Stage 2 is an appropriate time to add new methods. The major semantics are supposed to be settled at this point.)

**Comment by Jack-Works** [comment]
fine though I think it is very useful to make us `map` on a Map or something

**Comment by ljharb** [comment]
I agree, but that’s what follow up proposals are for.

**Comment by devsnek** [comment]
we are past the point of adding new methods, and have been for several months.
