### ISSUE TITLE
Would `Iterator.from` have an alias in `Array.prototype` ?

### ISSUE THREAD

**Issue by jRimbault** [tc39/proposal-iterator-helpers#129]
I mean adding a method to the array prototype like `toLazy` or `toIterator` :

```js
const squares = [1, 2, 3].toIterator().map(i => i * i).toArray();
```

Is that kind of change/addition in scope for this proposal ?

**Comment by bakkot** [comment]
`Array.prototype.values` already exists and does what you want.

**Comment by jRimbault** [comment]
Ah yes of course :)
