### ISSUE TITLE
Handle infinity case in ToIntegerOrInfinity

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-iterator-helpers#137]
raised in https://github.com/tc39/proposal-iterator-helpers/pull/135

> Incidentally, I note these operations are using ToInteger. That has been renamed to ToIntegerOrInfinity, which is what that AO has always done. The new name makes it clear that these have another editorial issue, which is that they don't correctly deal with being passed Infinity (they try to subtract 1 from it, which is not well-defined). I assume the intent is that passing Infinity means taking or dropping the whole iterator, so this could be resolved by just guarding the Set _remaining_ to _remaining_ - 1. lines by If _remaining_ is not +∞,.

**Comment by michaelficarra** [comment]
This is fixed by #139.
