### ISSUE TITLE
Are pre-checks done before async function machinery starts or after?

### ISSUE THREAD

**Issue by MadProbe** [tc39/proposal-iterator-helpers#154]
Issue: I see inconsistency in async non-generator %AsyncIterator.prototype%.*() function now how pre-checks work compared to async? generator functions and normal (sync, non-generator) ones.
Let's take a look at specification, for example, of %AsyncIterator.prototype%.take():
```
1. Let iterated be ? GetIteratorDirect(this value).
2. Let integerLimit be ? ToIntegerOrInfinity(limit).
3. If integerLimit < 0, throw a RangeError exception..
4. Let closure be a new Abstract Closure with no parameters that captures iterated and integerLimit and performs the following steps when called:
  // specification of function implementation...
5. Return ? CreateAsyncIteratorFromClosure(closure, Async Iterator Helper, %AsyncIteratorHelperPrototype%).
```
Checks are done before an async generator created and if errors are thrown, they are thrown before its creation, but not after programmer calls the `next` method of AsyncGenerator.
What we see in the specification, for example, of %AsyncIterator.prototype%.toArray():
```
%AsyncIterator.prototype%.toArray is a built-in async function which, when called, performs the following steps
  1. Let iterated be ? GetIteratorDirect(this value).
  2. Let items be a new empty List.
  3. Repeat,
    // specification...
```
There we see that `GetIteratorDirect(this value)` check is done **inside** of async function, so if check is thrown, it rejects the promise that async function creates and returns it, but not just thrown out from it. Was this intentional or am i just misreading the specification? And if i am just misreading it, could someone disambiguate this part of specification?
And i want to thank eveyone who will answer this question.

**Comment by devsnek** [comment]
The functions which return an iterator perform checks prior to that because otherwise they'd be delayed until `next` is called the first time.
