### ISSUE TITLE
Spec problem: AsyncIterator.from

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-iterator-helpers#159]
![image](https://user-images.githubusercontent.com/5390719/139829677-26e97ea4-8864-4497-a473-744926734808.png)

`CreateAsyncFromSyncIterator` returns a spec value `IteratorRecord` instead of `Iterator`. Do you mean `ii. Return ! CreateAsyncFromSyncIterator(syncIteratorRecord)[[iterator]].`?

**Comment by codehag** [comment]
Nice catch.

**Comment by bakkot** [comment]
Fixed by https://github.com/tc39/proposal-iterator-helpers/issues/172.
