### ISSUE TITLE
`flatMap` should close both iterators when `return`/`throw` are called, not just the outer one

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-iterator-helpers#163]
Consider:

```js

function* words() {
  try {
    yield 'abc';
    yield 'xyz';
  } finally {
    console.log('underlying iterator closed');
  }
}

let chars = words().flatMap(function* (arg) {
  try {
    yield* arg.split('');
  } finally {
    console.log('mapping iterator closed');
  }
});

for (let c of chars) {
  break;
}
```

I would expect this to print `'mapping iterator closed'` as well as `'underlying iterator closed'`. But it doesn't; only the underlying one gets closed.

This is related to #114, but more so: even the JS which that issue says is roughly equivalent to the current implementation would close the mapping iterator.

**Comment by hax** [comment]
I found that Firefox nightly actually work as your expect, though core-js implementation not.
