### ISSUE TITLE
groupToMap? 

### ISSUE THREAD

**Issue by hemanth** [tc39/proposal-iterator-helpers#178]
Does it make sense to have `iterable.groupToMap`?

**Comment by bakkot** [comment]
`groupBy` on iterators is often different from that on arrays - it groups runs of items which form a group, rather than consuming the whole thing into an object. (See [python](https://docs.python.org/3/library/itertools.html#itertools.groupby), e.g.)

**Comment by hemanth** [comment]
Ah, I was imaging it to be more like [asyncio.gather](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather).

**Comment by bakkot** [comment]
I haven't looked at `asyncio.gather` before and can't tell what behavior you're proposing. Can you say more concretely what you're hoping for? Would it be different from `.toArray().groupToMap()`, and, if so, how?

**Comment by hemanth** [comment]
`.toArray().groupToMap()` should suffice, closing this issues. Thank you.
