### ISSUE TITLE
toAllSettledArray?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-iterator-helpers#209]
`toArray()` on Async Iterator now looks like `Promise.all`, should we have a `toAllSettledArray` to match `Promise.allSettled` in case we want it not throwing?

**Comment by bakkot** [comment]
Once a promise yielded by an async iterator, the rest of the promises aren't normally going to settle at all. So I don't think that really makes sense.

**Comment by bergus** [comment]
I don't see a similarity. `Promise.all` deals with all promises at once (and doesn't support asynchronous iterators). `toArray()` handles the promises sequentially.

For a similar purpose as `allSettled`, a useful method could be `takeUntilError`, which ignores `next()` throwing (or rejecting, in case of async iterators) and just ends the iteration there.

**Comment by ljharb** [comment]
If your goal is a Promise combinator, these all take an iterator - why would you toArray it at all?

**Comment by Jack-Works** [comment]
I mean, it should take any `Iterator<Promise>` and return a `Promise<PromiseSettledResult[]>`.

But maybe a `toSettled()` is good, so we can: `arr.toSettled().toArray()`

**Comment by ljharb** [comment]
Why is `x.toSettled().toArray()` better than `Promise.allSettled(x)`?

**Comment by michaelficarra** [comment]
This doesn't seem sufficiently motivated.
