### ISSUE TITLE
taking Infinity or dropping 0

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-iterator-helpers#220]
Should `iter.take(Infinity)` or `iter.drop(0)` return `iter` instead of wrapping it unnecessarily?

**Comment by bakkot** [comment]
I would lean towards wrapping, for consistency. It's weird for the identity to depend on the precise value of an argument like this, and I can imagine code along the lines of

```js
let next = Iterator.HelperPrototype.next;
[...]
let skipped = base.drop(n);
[...]
next.call(skipped);
```
which would break if it happened to hit one of the special cases.

**Comment by michaelficarra** [comment]
Not totally convinced on this one, but I will admit it's unusual. Closing.
