### ISSUE TITLE
`asIndexedPairs` seems a bit long

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/proposal-iterator-helpers#23]
Could that be simplified to `withIndices` or `withIndex` instead? There is some precedent in Ruby for that naming.

**Comment by devsnek** [comment]
it is purposely given this verbose name because I am planning to bikeshed the name at the july meeting.

**Comment by bergus** [comment]
In many Java Stream libraries, the method seems to have the name `zipWithIndex` ([there's no native one](https://stackoverflow.com/q/18552005)).

**Comment by topaxi** [comment]
What about `entries()`? Other collections like Array, Map, Set already use this name.
