### ISSUE TITLE
`isIterable`?

### ISSUE THREAD

**Issue by Rudxain** [tc39/proposal-iterator-helpers#249]
IDK if this is in-scope/on-topic, but it would be really useful to have a function or static-method to check if an arbitrary value is iterable

**Comment by ljharb** [comment]
`typeof x[Symbol.iterator] === 'function'`?

**Comment by Josh-Cena** [comment]
> `typeof x[Symbol.iterator] === 'function'`

`@@iterator` also needs to return an object with a callable `next()` method that returns an object.

Still, IMO `iterable` has always been a protocol, like `thenable`—and protocols can hardly be reflectively checked for validity. It's unfair to lock people into a branded version of iterable while saying any userland iterable implemented as a plain object is "not an iterable.

**Comment by Rudxain** [comment]
> `typeof x[Symbol.iterator] === 'function'`?

I would prefer an "abstraction" for better readability. Specially because it's a common operation


> return an object with a callable `next()` method that returns an object

I forgot about that. That's another reason why an abstraction might be a good idea (because it's prone to bugs in userland)

**Comment by bakkot** [comment]
There's no way to check the "callable `next()` method that returns an object" property without actually invoking `.next()` (specifically the "returns an object" part), and you can't do that without side-effects. So you can't do it at all.

Honestly, `Symbol.iterator in x` seems fine to me. It's only going to have false positives if someone deliberately goes out of their way to have false positives (or _really_ messes up), and there's no way to eliminate all false positives anyway.

**Comment by Rudxain** [comment]
> There's no way to check the "callable `next()` method that returns an object"

True, but at least we can check if `next` is callable by using `typeof foo?.next == "function"`

> there's no way to eliminate all false positives anyway.

Unfortunately, that's true. It seems duck-typed iterators/generators are inevitable

**Comment by Josh-Cena** [comment]
There's no way to even verify the return type of `@@iterator` without possible side-effects...

**Comment by Rudxain** [comment]
> without possible side-effects...

Oh... right. Sorry. I forgot about that 😅

**Comment by zloirock** [comment]
> Honestly, `Symbol.iterator in x` seems fine to me.

It's always true for objects with polyfills like `get-own-property-symbols`, so `typeof x[Symbol.iterator] == 'function'` is better.

**Comment by Rudxain** [comment]
@michaelficarra Please close as "not planned", otherwise it's misleading

**Comment by michaelficarra** [comment]
I hate this feature.
