### ISSUE TITLE
map with async callback

### ISSUE THREAD

**Issue by vitaly-t** [tc39/proposal-iterator-helpers#259]
What happens when `map` callback returns a promise? I cannot surmise it from the spec.

**Comment by ljharb** [comment]
I believe that if it's the sync map, then the item yielded is a Promise. If it's async map, then it'd be awaited.

**Comment by bakkot** [comment]
Async iterables aren't meant to contain Promises directly. You can of course wrap the promise if you really want that anyway, the same way you would if you wanted to have a Promise for a Promise:

```js
Promise.race((await asyncIter().map(item => ({ value: someAsyncFn(item) })).toArray()).map(x => x.value))
```
But that's not going to be the default behavior.

**Comment by vitaly-t** [comment]
> Async iterables aren't meant to contain Promises directly

Async iterables are built on top of promises, and so is this additional spec.

One of the most popular subjects on concurrency is when a developer remaps a sequence into promises, and then tries to control the concurrency. This spec not only doesn't help with that, but more like disables it, by forcing sequential resolution. A bit of Achilles's heel, IMO.

Just saying.

**Comment by michaelficarra** [comment]
@vitaly-t Just map them into 1-tuples. For example, instead of

```js
asyncIterable.map(e => promiseReturningFunction(e))
```

do

```js
asyncIterable.map(e => [promiseReturningFunction(e)])
```

... and then "unbox" it when you handle it later. It's kinda gross, but that's just how the language works. Deviating from it would be way worse. I am with you: promises being "auto-flattened" is one of the worst design decisions ever made for JavaScript (and that's saying something), but we must look past it and live with our kludges.

**Comment by pinko-fowle** [comment]
This seems like quite a large systematic problem, far beyond map, that will make many people very unhappy.

There are decent enough solutions for `map`. However if we turn to other functions like `filter`, not having an async filterFn seems like a potential major dealbreaker. It can be worked around, but only with much pain.

**Comment by bakkot** [comment]
@pinko-fowle The version of filter on `asyncIterator` is in fact async, so I don't understand your comment.
