### ISSUE TITLE
Are sync iterator helpers supposed to pass through the returned value?

### ISSUE THREAD

**Issue by syg** [tc39/proposal-iterator-helpers#269]
```javascript
function* G() {
  return 42;
}
G().map(x => x).next().value; // undefined, but should it be 42?
```

**Comment by ljharb** [comment]
Is https://github.com/tc39/proposal-iterator-helpers/issues/122#issuecomment-1176946383 relevant?

**Comment by zloirock** [comment]
It was discussed many times - for example, here https://github.com/tc39/proposal-iterator-helpers/issues/217

**Comment by syg** [comment]
> Is https://github.com/tc39/proposal-iterator-helpers/issues/122#issuecomment-1176946383 relevant?

Perfect, thanks.

**Comment by syg** [comment]
@zloirock Thanks for #217 also. Closing as intended.
