### ISSUE TITLE
Why `Iterator.from` does not allow primitives?

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-iterator-helpers#33]
`Iterator.from(string) -> string iterator`?

**Comment by devsnek** [comment]
that should work just fine, because strings have `Symbol.iterator`.

**Comment by zloirock** [comment]
> `If Type(O) is not Object, throw a TypeError exception.`

**Comment by ljharb** [comment]
Indeed, that should RequireObjectCoercible first, and then ToObject.

**Comment by ljharb** [comment]
Fixed in https://github.com/tc39/proposal-iterator-helpers/commit/66d8d49a1867f091bcea812c565ba44b15c4e817 ?
