### ISSUE TITLE
Validation of arguments missed in many methods

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-iterator-helpers#35]
For example, compare [`Iterator.prototype.forEach`](https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype-foreach) and [`Array.prototype.forEach`](https://tc39.es/ecma262/#sec-array.prototype.foreach) - missed, at least, validation of a callback.

**Comment by devsnek** [comment]
Yeah that's on the plan, I've been trying to get the initial algorithms out before worrying about arg checks and conversions and stuff like that.
