### ISSUE TITLE
`.take` and fractional numbers

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-iterator-helpers#37]
It should not use just `ToNumber` conversion or `is 0` check, since:
```js
Iterator.from([1, 2, 3, 4]).take(2.5).toArray() // => [1, 2, 3, 4]
```

**Comment by zloirock** [comment]
The same for `.drop`.

**Comment by c69** [comment]
should it trim to integer part or throw ?

**Comment by devsnek** [comment]
in the spec we generally convert to an int and throw if the number is different.
