### ISSUE TITLE
New champion?

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-iterator-helpers#52]
Looking at https://github.com/tc39/proposals/pull/242, this proposal no longer has a champion.

**Comment by michaelficarra** [comment]
I'll step in unless someone feels strongly that they should or I should not.

**Comment by leobalter** [comment]
@michaelficarra If I'm not wrong, @devsnek has been working on this proposal and I believe it's the best for you both to coordinate this.

**Comment by devsnek** [comment]
@michaelficarra if you're ok with the current direction of this proposal, i'd appreciate it. there's also the built-in generators stuff that has to be presented and discussed with this.

**Comment by decompil3d** [comment]
I'd also be happy to be involved given my work on https://github.com/tc39/proposal-object-map which likely will lean on some of the features involved in this proposal.

**Comment by devsnek** [comment]
There can be multiple champions :)

Just make sure you agree with all of the stuff this proposal is doing, cuz I want to ask for stage 3 at some point soonish.

**Comment by decompil3d** [comment]
Sounds good. @michaelficarra want to co-champion this with me? I will likely be remote for the Dec meeting, and in-person in Feb, June, and July.

**Comment by michaelficarra** [comment]
@decompil3d Yeah sure.

**Comment by decompil3d** [comment]
@michaelficarra @devsnek Awesome. Let's do this then:

- Here's a PR to apply Michael & myself as champions: https://github.com/tc39/proposals/pull/246
- @devsnek - if you could please add us as contributors on the proposal repo, that'd be helpful
- Let's consider meeting on a call of some sort to discuss where this proposal is at and what's remaining ahead of stage 3. Any preferences on dates/times/etc?

And, for reference, I have adjusted my [Object map proposal](https://github.com/tc39/proposal-object-map) to become more of an extension to this one. So I'd like to help get this one done with and then work towards extending to support Objects later on.

**Comment by michaelficarra** [comment]
@decompil3d Let's coordinate timing via email or other private means.
