### ISSUE TITLE
Iterator.prototype.constructor

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-iterator-helpers#60]
Now it's `Object`, maybe it should be `Iterator`?

**Comment by zloirock** [comment]
Theoretically, it could be a breaking change since could affect some old code:
```js
[].values().constructor; // => Object
```
but unlikely that someone used it.

**Comment by michaelficarra** [comment]
Can you give some examples of why it would be useful to do this?

**Comment by ljharb** [comment]
Because `[].values() instanceof Iterator` should be true.

**Comment by zloirock** [comment]
JS objects contain `.constructor` and if it's already a part of the objects model, we should not forget about. Someone uses it for identification of objects, someone for subclassing. I'm not a fan of active usage of this property, but since some libraries and developers use it...

**Comment by michaelficarra** [comment]
@ljharb `Iterator[@@hasInstance]`?

**Comment by devsnek** [comment]
OrdinaryHasInstance of `o` and `C` uses `C.prototype`, not `o.constructor`. That being said, I don't really see any reason not to update the constructor property. I seriously doubt it would break anyone.

**Comment by michaelficarra** [comment]
Okay so is there any tangible benefit to making this change? Is it just for consistency?

**Comment by zloirock** [comment]
@michaelficarra since we must respect the concepts that are already used in the language?

**Comment by ljharb** [comment]
Consistency is a tangible benefit.

(yes, `Symbol.hasInstance` would help, but why when we could fix the prototype and the constructor)

**Comment by zloirock** [comment]
@ljharb `@@hasInstance` is not required, the prototype already added and [your example](http://es6.zloirock.ru/#log(%5B%5D.values()%20instanceof%20Iterator)) already works with this proposal.
