### ISSUE TITLE
Revert type assertions in %AsyncFromSyncIteratorPrototype% methods

### ISSUE THREAD

**Issue by jorendorff** [tc39/proposal-iterator-helpers#66]
https://tc39.es/ecma262/#sec-%asyncfromsynciteratorprototype%.next

These methods used to throw TypeError if **this** was the wrong type, but someone must have noticed that these objects are never exposed to user code, and the type checks in the spec were changed to assertions.

However, `AsyncIterator.from` will create a way to expose these objects to user code, so that their methods can be misapplied. I think this proposal needs to reinstate the type checks... assuming these methods aren't [removed from ECMA-262 entirely](https://github.com/tc39/ecma262/issues/1765).

**Comment by devsnek** [comment]
good catch, will fix.
