### ISSUE TITLE
Consider specifying %WrapForValidIteratorPrototype% as a generator like all other helpers

### ISSUE THREAD

**Issue by jorendorff** [tc39/proposal-iterator-helpers#67]
Also %WrapForValidAsyncIteratorPrototype%.

Rationale: It just seems more consistent? This isn't super important; feel free to close if it's just too late.

**Comment by ExE-Boss** [comment]
The issue here is that `%WrapForValidIteratorPrototype%` and `%WrapForValidAsyncIteratorPrototype%` simply wrap an existing iterator object and forward calls to it, which wouldn’t make sense to be implemented as a generator.
