### ISSUE TITLE
Add filterOut?

### ISSUE THREAD

**Issue by hax** [tc39/proposal-iterator-helpers#72]
Consider https://github.com/tc39-transfer/proposal-array-filtering proposal, shall we also add `filterOut` for iterator in this proposal?

**Comment by c69** [comment]
i think getting the core behavior right and getting the initial set of operators out of the door is priority number one.

Once this proposal is standartized and Array.prototype gets new convenience methods, maybe people of the future can add more iterator helpers.

**Comment by decompil3d** [comment]
Agree with @c69 -- `filterOut` is not yet at stage 2, and meanwhile this proposal is already close to stage 3. I may end up championing a follow-up proposal to this one to add additional helpers if/when this initial proposal makes it through the process. So we can re-consider then.
