### ISSUE TITLE
Union and set difference?

### ISSUE THREAD

**Issue by kevinbarabash** [tc39/proposal-iterator-helpers#77]
This proposal adds `intersection`.  Why not include `union` and `setDiff` as well?

**Comment by ljharb** [comment]
A union/concat operation seems nice.

**Comment by devsnek** [comment]
This proposal does not include `intersection`, and we're definitely already at capacity for methods.

**Comment by decompil3d** [comment]
I agree that these would be nice. As mentioned, this proposal is already approved for stage 2 and thus it is unlikely to be able to accept additional methods at this time. I may end up championing a follow-up proposal to add subsequent helpers like union, setDiff, filterOut/reject (if that makes it into arrays), etc. So perhaps we can just wait for that.
