### ISSUE TITLE
Prior Art: lodash

### ISSUE THREAD

**Issue by xmedeko** [tc39/proposal-iterator-helpers#84]
Prior Art mention [lodash](https://www.npmjs.com/package/lodash), but IMO lodash at the current version 4.17.15 does not have any function working with iterators or iterables, they have to be converted to Array first, see https://github.com/lodash/lodash/issues/737

**Comment by slikts** [comment]
Lodash is "prior art" in the broader sense of iteration, not ES6 iteration protocols.
