### ISSUE TITLE
Definition of "product" in prior art

### ISSUE THREAD

**Issue by leopiccionia** [tc39/proposal-iterator-helpers#85]
In the prior art comparison, it's cited that both Rust and Python implement `product`.

The definition of `product` in those cases are very different:
* In Rust, [`product`](https://doc.rust-lang.org/1.26.0/std/iter/trait.Product.html) is a reducer that returns the [product of the elements of a sequence (Π)](https://en.wikipedia.org/wiki/Multiplication#Capital_pi_notation).
* In Python, [`product`](https://docs.python.org/2/library/itertools.html#itertools.product) returns the [Cartesian product](https://en.wikipedia.org/wiki/Cartesian_product) of two iterators.

Mixing those concepts defeats the purpose of the comparison table, in my opinion, as the ES iterators helpers could contain either or both.

**Comment by devsnek** [comment]
the proposal contains neither, but thank you for the correction. I think I'll delete the table in a bit.
