### ISSUE TITLE
Possible intersection with protocol proposal

### ISSUE THREAD

**Issue by devsnek** [tc39/proposal-iterator-helpers#9]
Exposing `Iterator.prototype` and `Iterator.asyncPrototype` may intersect with the design of https://github.com/michaelficarra/proposal-first-class-protocols.

I assume if protocols happen, `%IteratorPrototype%` would exist only to implement an `Iterator` protocol, and creating your own manual iterator would implement `Iterator` instead of having a prototype of `%IteratorPrototype%`.

```js
const myAmazingIterator = { next() {} };

Object.setPrototypeOf(myAmazingIterator, Iterator.prototype);
// or
Protocol.implement(myAmazingIterator, IteratorProtocolFromSomewhere);
```

cc @michaelficarra

**Comment by zloirock** [comment]
```js
class MyAmazingIterator extends Iterator { /* ... */ }
```
looks much better.

In [an alternative proposal](https://github.com/leebyron/ecmascript-iterator-hof), `Iterator` is a function, not just a namespace, so why not make it a function here?

**Comment by michaelficarra** [comment]
@zloirock Don't forget that the protocols proposal includes syntax for implementing a protocol declaratively within a class, allowing you to reserve the class inheritance position for actual class inheritance. For example,

```js

class MyAmazingIterator {
  /* ... */
  implements protocol Iterator {
    /* ... */
  }
}
```

Also remember the syntax is still very early stage and intentionally verbose.

**Comment by zloirock** [comment]
@michaelficarra my comment was not related protocols proposal. Protocols proposal is an interesting feature, but I just mean that classical prototype inheritance looks more logical here.
